export const DISPUTED_TRANSACTIONS_DATA = [
  {
    id: 1,
    title: 'Successful but not credited',
    description: 'I made a transfer to this account but it didn\'t reflect...',
    recipient: 'Rejoice Regina Rose',
    date: '18th Oct, 2025',
    amount: 'N3,000,000',
    status: 'Pending',
    // Details data
    walletAccountNo: "Wallet Account No.",
    balance: "N100,000",
    recipientDetails: "Rejoice Regina Rose | Safe Haven | 089241526",
    disputeType: "Successful but not credited",
    transactionDate: "18th October, 2025 | 08:00 AM",
    dateSent: "18th October, 2025 | 09:00 AM",
    transactionId: "100273637AGGSHG7",
    category: "Transfer",
    disputeStatus: "Pending",
    transactionStatus: "Expired",
    shortDescription: "I made a transfer to this account but didn't get credited",
    reasonForDeclining: "I believe this transfer was successful from our ends please reach out to the recipient bank to log a complaint.",
    imageUrl: "" 
  },
  {
     id: 2,
     title: 'Successful but not credited',
     description: 'I made a transfer to this account but it didn\'t reflect...',
     recipient: 'Rejoice Regina Rose',
     date: '18th Oct, 2025',
     amount: 'N3,000,000',
     status: 'Pending',
     // Details data - replicating for mock
     walletAccountNo: "Wallet Account No.",
     balance: "N100,000",
     recipientDetails: "Rejoice Regina Rose | Safe Haven | 089241526",
     disputeType: "Successful but not credited",
     transactionDate: "18th October, 2025 | 08:00 AM",
     dateSent: "18th October, 2025 | 09:00 AM",
     transactionId: "100273637AGGSHG7",
     category: "Transfer",
     disputeStatus: "Pending",
     transactionStatus: "Expired",
     shortDescription: "I made a transfer to this account but didn't get credited",
     reasonForDeclining: "",
     imageUrl: ""
   },
   {
     id: 3,
     title: 'Successful but not credited',
     description: 'I made a transfer to this account but it didn\'t reflect...',
     recipient: 'Rejoice Regina Rose',
     date: '18th Oct, 2025',
     amount: 'N3,000,000',
     status: 'Pending',
     // Details data - replicating for mock
     walletAccountNo: "Wallet Account No.",
     balance: "N100,000",
     recipientDetails: "Rejoice Regina Rose | Safe Haven | 089241526",
     disputeType: "Successful but not credited",
     transactionDate: "18th October, 2025 | 08:00 AM",
     dateSent: "18th October, 2025 | 09:00 AM",
     transactionId: "100273637AGGSHG7",
     category: "Transfer",
     disputeStatus: "Pending",
     transactionStatus: "Expired",
     shortDescription: "I made a transfer to this account but didn't get credited",
     reasonForDeclining: "",
     imageUrl: ""
   }
];
